language: csharp
solution: "./Promises/Promises.sln"
install:
- sudo apt-get install dotnet-sdk
- nuget restore ./Promises/Promises.sln
script:
- msbuild /p:Configuration=Debug ./Promises/Promises.sln 
- dotnet vstest ./Promises/Promises.Tests/bin/Debug/Promises.Tests.dll /InIsolation /logger:trx