os: osx
language: csharp
solution: "./Promises/Promises.sln"
install:
- brew tap caskroom/cask
- brew cask install dotnet
- dotnet restore ./Promises/Promises.sln
script:
- msbuild /p:Configuration=Debug ./Promises/Promises.sln 
- dotnet vstest ./Promises/Promises.Tests/bin/Debug/Promises.Tests.dll /InIsolation /logger:trx