os: osx
language: csharp
dotnet: 2.1.300
mono: latest
solution: "./Promises/Promises.sln"
env:
  - UNITY_DOWNLOAD_CACHE="$(pwd)/unity_download_cache"
  - UNITY_PATH="/Applications/Unity/Unity.app/Contents/MacOS/Unity"
cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE
before_install:
  - chmod a+x ./Scripts/*.sh
install:
  - nuget restore ./Promises/Promises.sln
  - pip install ugetcli
  - nuget setapikey $NUGET_API_KEY -Source https://api.nuget.org/v3/index.json 
script: 
  - ./Scripts/test.sh
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./Scripts/deploy.sh; fi
