os: osx
language: csharp
dotnet: 2.1.300
solution: "./Promises/Promises.sln"
install:
- nuget restore ./Promises/Promises.sln
- brew install python
- pip install ugetcli
- nuget setapikey $NUGET_API_KEY -Source https://api.nuget.org/v3/index.json 
script:
- ./Scripts/test.sh
- if [ "$TRAVIS_BRANCH" = "master" ]; then ./Scripts/deploy.sh; fi
