os: windows
language: csharp
dotnet: 2.1.300
solution: "./Promises/Promises.sln"
install:
- nuget restore ./Promises/Promises.sln
script:
- msbuild /p:Configuration=Debug ./Promises/Promises.sln 
- dotnet vstest ./Promises/Promises.Tests/bin/Debug/Promises.Tests.dll /InIsolation /logger:trx